export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE";


//post

// export const EDIT_BOOK_REQUEST = "EDIT_BOOK_REQUEST";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";
// export const EDIT_BOOK_FAILURE = "EDIT_BOOK_FAILURE";